version: '3.7'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    environment:
      - TZ=Europe/Berlin
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the BasicAuth usersFile into the container
      - ./config/.htpasswd:/auth/.htpasswd:ro
      # Map the static configuration into the container
      - ./config/static.yml:/etc/traefik/traefik.yml:ro
      # Map the dynamic configuration into the container
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # Map the certificats into the container
      - ./certs:/etc/certs:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
